Project
s0kil/Positioning-Floating-Elements pull request #1
Opened 2019-12-02 15:21 UTC by s0kil

2019-12-02 21:41 UTC, pelzolga123 commented on style.css
> +  /* line-break: loose; */
Commented code needs to be deleted.

2019-12-02 21:42 UTC, pelzolga123 commented on index.html
> +    -->
Commented code needs to be deleted.

2019-12-02 21:42 UTC, pelzolga123 requested changes
Project needs corrections.

2019-12-02 21:42 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!
But there are some changes needed: 
* [ ] Please add descriptive name and project description to your pull request. [Link to example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
* [ ] The NY Times logo in navbar should be a link.
* [ ] All elements of navbar should be aligned properly. Right now left side is higher than others.
![image](https://user-images.githubusercontent.com/20416431/69995569-03e78a80-1559-11ea-8ab1-c45d43508911.png)
* [ ] Navbar should have a fixed position (it sticks to the top part of the screen).
* [ ] 'Theory of inflation' part is not aligned like an original one:
![image](https://user-images.githubusercontent.com/20416431/69996129-17dfbc00-155a-11ea-8a4c-44b56727c4f3.png)
Original:
![image](https://user-images.githubusercontent.com/20416431/69996256-537a8600-155a-11ea-95eb-c1c36066cfa0.png)
* [ ] Comment part should be aligned with article like in original website.
![image](https://user-images.githubusercontent.com/20416431/69996561-fa5f2200-155a-11ea-871f-bc1d0ff3731f.png)
* [ ] This sections are missing:
![image](https://user-images.githubusercontent.com/20416431/69996750-5aee5f00-155b-11ea-99b5-1fc4dd867817.png)
![image](https://user-images.githubusercontent.com/20416431/69996867-99841980-155b-11ea-92ad-c662d9f706e2.png)
* [ ] Aside parts are missing:
![image](https://user-images.githubusercontent.com/20416431/69997306-8756ab00-155c-11ea-85fe-e98ca4d9c5f0.png)
![image](https://user-images.githubusercontent.com/20416431/69997394-bf5dee00-155c-11ea-95b8-1df13d629e20.png)
* [ ] Commented code needs to be deleted.

### Please kindly Fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack. *Happy coding*

2019-12-03 21:08 UTC, mosesogwo requested changes
## :clap: You are doing a good job.
However, you still need to address the following:

- The aside section is not properly aligned.
## **Your project:**
![image](https://user-images.githubusercontent.com/46611870/70089213-fa712780-1617-11ea-9892-27fac7db5f9e.png)

## **Original:**
![image](https://user-images.githubusercontent.com/46611870/70089296-1d034080-1618-11ea-807e-e97f0dc03576.png)

## **Your project:**
![image](https://user-images.githubusercontent.com/46611870/70089382-3dcb9600-1618-11ea-8fbd-2dbcc1b57b59.png)


## **Original:**
![image](https://user-images.githubusercontent.com/46611870/70089437-5c319180-1618-11ea-816c-db0030a1e97b.png)

- The title of your README is for the Forms project and not this project.

- You haven't added a description to this pull request as requested in the last review.

### Kindly make these changes and submit another code review request.

### You are almost there. Keep up the good work.

**Status: Changes requested**

2019-12-03 22:32 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2019-12-03 22:44 UTC, Anna-Myzukina commented
### Hi team!
### Wow! The project looks really very good! The readme file is so descriptive! :+1:  

### But still needs changes.
Kindly recommended checking HTML markup with this validator https://validator.w3.org/#validate_by_upload.

![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png)

Now it shows errors in your project

![12](https://user-images.githubusercontent.com/26605804/70096072-e1c03c00-162e-11ea-8c94-075b325afd91.png)
 
##### Footer

* [ ] It should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

* Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). 
* Pull Request should have a meaningful title and a short description [General requirements](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/).
 I hope in the next project you can do this! ![image](https://user-images.githubusercontent.com/26605804/70094553-6b6e0a80-162b-11ea-951e-d8d0a6338d70.png)


![screen](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

2019-12-03 22:47 UTC, Anna-Myzukina requested changes
Kindly recommended fix errors in HTML file, make footer sticks to the bottom part of the screen

2019-12-03 23:05 UTC, s0kil commented
@Anna-Myzukina Hello Anna, We have tested the project once again and the footer is aligned properly.
![Screenshot from 2019-12-03 18-03-55](https://user-images.githubusercontent.com/24403355/70097472-7ad36080-15f7-11ea-950c-a04ee91bdcaa.png)

2019-12-04 15:54 UTC, Oluwadamilareolusakin commented
# Great work team! :rocket: 
You may merge this PR and move on with your projects :+1: .

2019-12-04 15:54 UTC, merged